=== jhmaverick/blazar/src/schema/blazar-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "fileMatch": ["blazar-manifest.json", "custom-manifest.json"],
  "name": "blazar-manifest",
  "type": "object",
  "version": "1.0",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "configs": {
      "type": "object",
      "description": "Application settings",
      "additionalProperties": false,
      "properties": {
        "env": {
          "type": "integer",
          "default": 1,
          "description": "Define current environment",
          "enum": [1, 2, 3]
        },
        "force_https": {
          "type": "boolean",
          "default": false,
          "description": "Set true to force https in production"
        },
        "force_www": {
          "type": "integer",
          "default": 0,
          "description": "Use www",
          "enum": [-1, 0, 1]
        },
        "max_img_width": {
          "type": "integer",
          "default": 1920,
          "description": "Max image width to upload and render"
        },
        "max_img_height": {
          "type": "integer",
          "default": 1080,
          "description": "Max image height to upload and render"
        },
        "max_upload_filesize": {
          "type": "string",
          "default": "10MB",
          "description": "Max filesize to upload"
        },
        "texts_dir": {
          "type": "string",
          "description": "Directory to texts files"
        },
        "logs_dir": {
          "type": "string",
          "description": "Directory to logs files"
        },
        "save_logs": {
          "type": "string",
          "default": "json",
          "enum": ["all", "json", "html", "none"]
        },
        "cors": {
          "type": ["string", "null"],
          "default": null,
          "description": "Enable cors for domain"
        },
        "view_render_mustache": {
          "type": "boolean",
          "default": false,
          "description": "Use mustache template as default in view render"
        },
        "console_url": {
          "type": "string",
          "default": "http://localhost:4000",
          "description": "URI to send logs",
          "format": "uri"
        }
      }
    },
    "data": {
      "type": "object",
      "description": "Application data"
    },
    "dbs": {
      "type": "object",
      "description": "Databases",
      "additionalProperties": {
        "$ref": "#/definitions/db"
      }
    },
    "map": {
      "$ref": "#/definitions/map_list"
    }
  },
  "definitions": {
    "db": {
      "type": "object",
      "additionalProperties": false,
      "required": ["host", "user", "pass", "db"],
      "properties": {
        "drive": {
          "type": "string",
          "default": "mysql"
        },
        "host": {
          "type": "string"
        },
        "user": {
          "type": "string"
        },
        "pass": {
          "type": "string"
        },
        "db": {
          "type": "string"
        },
        "port": {
          "type": "string"
        },
        "socket": {
          "type": "string"
        }
      }
    },
    "map_list": {
      "type": "object",
      "description": "",
      "minProperties": 1,
      "patternProperties": {
        "^[a-zA-Z0-9_-]*$": {
          "$ref": "#/definitions/map"
        }
      },
      "additionalProperties": false
    },
    "map": {
      "additionalProperties": true,
      "required": ["class"],
      "properties": {
        "class": {
          "type": "string",
          "description": ""
        },
        "sub": {
          "$ref": "#/definitions/map_list"
        }
      }
    }
  }
}

=== jhmaverick/blazar/dev-project/blazar-manifest.json
{
  "$schema": "../schema/blazar-schema.json",
  "configs": {
    "env": 3,
    "logs_dir": "../logs",
    "console_url": "http://blazar-logs:4000"
  },
  "data": {
  },
  "dbs": {
    "main_db": {
      "drive": "mysql",
      "host": "blazar-mariadb",
      "user": "root",
      "pass": "root",
      "db": "blazar-dev"
    }
  },
  "map": {
    "home": {
      "class": "BlazarDev\\Pages\\Home\\Home"
    },
    "pg_midias": {
      "class": "BlazarDev\\Pages\\Midias\\Midias"
    },
    "db": {
      "class": "BlazarDev\\Pages\\DB\\DB"
    },
    "singleapi": {
      "class": "BlazarDev\\SingleAPI\\SingleAPI"
    },
    "restful": {
      "class": "BlazarDev\\RESTful\\RESTful",
      "restful": true
    },
    "multiapi": {
      "class": "BlazarDev\\MultiAPI\\MultiAPI",
      "sub": {
        "teste1": {
          "class": "BlazarDev\\MultiAPI\\APIs\\Teste1"
        },
        "teste2": {
          "class": "BlazarDev\\MultiAPI\\APIs\\Teste2"
        }
      }
    },
    "midias": {
      "class": "BlazarDev\\Midias"
    }
  }
}

=== jhmaverick/blazar/test/blazar-manifest.json
{
  "$schema": "../schema/blazar-schema.json",
  "configs": {
    "logs_dir": "../logs"
  },
  "data": {
  },
  "dbs": {
    "main_db": {
      "drive": "mysql",
      "host": "localhost",
      "user": "root",
      "pass": "",
      "db": "dbexample"
    }
  },
  "map": {
    "home": {
      "class": "TestApp\\Pages\\Home\\Home"
    },
    "pg_midias": {
      "class": "TestApp\\Pages\\Midias\\Midias"
    },
    "db": {
      "class": "TestApp\\Pages\\DB\\DB"
    },
    "singleapi": {
      "class": "TestApp\\SingleAPI\\SingleAPI"
    },
    "multiapi": {
      "class": "TestApp\\MultiAPI\\MultiAPI",
      "sub": {
        "teste1": {
          "class": "TestApp\\MultiAPI\\APIs\\Teste1"
        },
        "teste2": {
          "class": "TestApp\\MultiAPI\\APIs\\Teste2"
        }
      }
    },
    "midias": {
      "class": "TestApp\\Midias"
    }
  }
}

=== jhmaverick/blazar/demo/pages/blazar-manifest.json
{
  "$schema": "../../src/schema/blazar-schema.json",
  "configs": {
    "force_https": false,
    "force_www": 0,
    "max_img_width": 1920,
    "max_img_height": 1080,
    "max_upload_filesize": "10MB",
    "logs_dir": "../logs",
    "cors": "*"
  },
  "data": {
  },
  "dbs": {
    "principal": {
      "drive": "mysql",
      "host": "localhost",
      "user": "",
      "pass": "",
      "db": ""
    }
  },
  "map": {
    "pages": {
      "class": "Application\\PageController",
      "sub": {
        "home": {
          "class": "Application\\Pages\\Home"
        },
        "page2": {
          "class": "Application\\Pages\\Page2"
        }
      }
    }
  }
}
